### ISSUE TITLE
[CSGO] [Request] Make plugin not use custom files

### ISSUE THREAD

**Issue by Uronic** [AlexSbyshko/SoccerJam#1]
Instead of using a custom ball model, the CSGO included soccer ball model can be used. The sound can be disabled or removed via cvar.

Just to avoid csgo players getting third party file error when matchmaking

**Comment by AlexSbyshko** [comment]
done :)

Changed ball model in config, deleted old ball model

**Comment by Uronic** [comment]
Nice! How about the sound file?

**Comment by Uronic** [comment]
Nevermind. I realized its not used in the csgo config. Thanks.
