### ISSUE TITLE
[CSGO] Fix Turbo Ability HUD Indicator 

### ISSUE THREAD

**Issue by Uronic** [AlexSbyshko/SoccerJam#2]
I remember, on previous CSGO updates prior to the new Panorama HUD, that there was a Turbo indicator in the HUD showing you how much of it was left when you pressed G to activate it.

Now, due to Panorama (I think), this doesn't work anymore.

**Comment by Uronic** [comment]
I found this on alliedmods.net, they are having the same issue.
https://forums.alliedmods.net/showthread.php?t=313781

**Comment by AlexSbyshko** [comment]
Should be fixed now in the new release

**Comment by Uronic** [comment]
Thanks it works!
